[project]
name = "jevdb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.5.0",
    "duckdb>=1.5.6",
    "polars>=1.44.2",
    "python-dotenv>=1.2.3",
]

[dependency-groups]
notebooks = [
    "ipykernel>=7.4.0",
    "jupyterlab>=4.6.4",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "seaborn>=0.13.2",
]
